import "./style.css";import {createClient} from "@supabase/supabase-js";
const supabase=createClient("https://gzgngkywjyanxicmwxlc.supabase.co","sb_publishable_Jyr7D3mH7WRXfG5V1v7gcw_I3QhtL3j");
const state={view:"home",user:null,rooms:[{id:"K001",name:"غرفة الملوك",game:"طرنيب",players:2,max:4},{id:"K002",name:"سهرة الأبطال",game:"طرنيب",players:1,max:4},{id:"K003",name:"تحدي سريع",game:"طرنيب",players:4,max:4}]};
const app=document.querySelector("#app");const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const card=r=>'<article class="room"><div class="room-top"><span class="badge">'+r.game+'</span><span class="'+(r.players>=r.max?"red":"green")+'">'+(r.players>=r.max?"ممتلئة":"● مفتوحة")+'</span></div><h3>'+esc(r.name)+'</h3><div class="room-meta"><span>🎴 '+r.game+'</span><span>👥 '+r.players+'/'+r.max+'</span><span>#'+r.id+'</span></div><button class="'+(r.players>=r.max?"disabled":"gold")+' join" data-id="'+r.id+'" '+(r.players>=r.max?"disabled":"")+'>'+(r.players>=r.max?"الغرفة ممتلئة":"انضم للغرفة")+'</button></article>';
function render(){let c=state.view==="home"?'<section class="hero"><div><span class="eyebrow">مملكة اللعب الجماعي</span><h1>الملوك</h1><p>تسجيل حقيقي، حساب دائم، وغرف لعب جماعية.</p><div class="actions"><button class="gold big" id="start">ابدأ اللعب</button><button class="ghost big" id="roomsBtn">الغرف</button></div></div><div class="crown">♛</div></section><section class="stats"><div><b>🎮</b><strong>غرف اللعب</strong><span>أنشئ أو انضم</span></div><div><b>🔐</b><strong>حساب حقيقي</strong><span>بريد وكلمة مرور</span></div><div><b>🃏</b><strong>طرنيب</strong><span>أول لعبة</span></div></section>':state.view==="rooms"?'<section class="page"><div class="page-head"><div><span class="eyebrow">اللعب الآن</span><h1>غرف اللعب</h1><p>اختر غرفة مفتوحة أو أنشئ غرفة.</p></div><button id="create" class="gold big">＋ إنشاء غرفة</button></div><div class="room-grid">'+state.rooms.map(card).join("")+'</div></section>':'<section class="page centered"><div class="profile-card"><div class="avatar">👑</div><span class="eyebrow">حساب الملوك</span><h1>'+esc(state.user?.email||"ضيف")+'</h1><p>حسابك محفوظ عبر نظام المصادقة الحقيقي.</p><button id="logout" class="ghost big">تسجيل الخروج</button></div></section>';app.innerHTML='<header class="top"><div class="brand">👑 <b>الملوك</b></div><nav><button id="homeBtn">الرئيسية</button><button id="navRooms">غرف اللعب</button><button id="navProfile">حسابي</button></nav><button id="loginBtn" class="gold">'+(state.user?"👤 حسابي":"دخول / تسجيل")+'</button></header><main>'+c+'</main><footer>الملوك © 2026</footer>';
document.querySelector("#homeBtn").onclick=()=>{state.view="home";render()};document.querySelector("#navRooms").onclick=()=>{state.view="rooms";render()};document.querySelector("#navProfile").onclick=()=>{state.view="profile";render()};document.querySelector("#loginBtn").onclick=()=>state.user?state.view="profile":auth();document.querySelector("#start")?.addEventListener("click",()=>{state.view="rooms";render()});document.querySelector("#roomsBtn")?.addEventListener("click",()=>{state.view="rooms";render()});document.querySelector("#create")?.addEventListener("click",createRoom);document.querySelector("#logout")?.addEventListener("click",logout);document.querySelectorAll(".join").forEach(b=>b.onclick=()=>join(b.dataset.id));}
async function auth(){const email=prompt("البريد الإلكتروني:");if(!email)return;const password=prompt("كلمة المرور (6 أحرف على الأقل):");if(!password)return;const mode=confirm("مستخدم جديد؟ اضغط موافق للتسجيل، وإلغاء لتسجيل الدخول.");let r=mode?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(r.error){alert(r.error.message);return}state.user=r.data.user;alert(mode&&!r.data.session?"تم إنشاء الحساب. تحقق من بريدك لتأكيد الحساب.":"تم تسجيل الدخول.");render()}
async function logout(){await supabase.auth.signOut();state.user=null;render()}
function join(id){if(!state.user){auth();return}const r=state.rooms.find(x=>x.id===id);if(r&&r.players<r.max){r.players++;alert("انضممت إلى "+r.name);render()}}
function createRoom(){if(!state.user){auth();return}const n=prompt("اسم الغرفة:","غرفة الملوك");if(n?.trim()){state.rooms.unshift({id:"K"+(Math.floor(Math.random()*900)+100),name:n.trim(),game:"طرنيب",players:1,max:4});render()}}
supabase.auth.getSession().then(({data})=>{state.user=data.session?.user||null;render()});supabase.auth.onAuthStateChange((_e,s)=>{state.user=s?.user||null;render()});